name: Deploy to Vercel

# Trigger this workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The environment where this job will run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0' # This matches your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy to Vercel using Vercel CLI
      - name: Deploy to Vercel
        run: npx vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
